@startuml
skinparam backgroundColor #FEFEFE
skinparam ArrowColor #333333

|#E3F2FD|Конвейер A (Передающий)|
|#E8F5E9|Конвейер B (Принимающий 1)|
|#FFF3E0|Конвейер C (Принимающий 2)|
|#F3E5F5|VirtualTransmitter|

|Конвейер A (Передающий)|
start
:задать тег отправки;
:регистрация тега;
|VirtualTransmitter|
:Создать слот;
:txRegistered = true;
|VirtualTransmitter|
:увеличение счётчика получателей;

|Конвейер A (Передающий)|
:получение данных;
:отправка данных;
|VirtualTransmitter|
if (предыдущая итерация завершена?) then (да)
    :новый слот;
    :обнуление счётчика;
    :рассылка сообщений;
else (нет)
    :ожидание завершени;
    :новый слот;
    :рассылка сообщений;
endif

|Конвейер B (Принимающий 1)|
:ожидание данных;
|VirtualTransmitter|
if (данные пришли?) then (да)
    :увеличение счётчика;
    if (получателей больше одного?) then (да)
        :отправить копию;
    else (нет — последний)
        :отпавить объект;
        :обнулить слот;
    endif
else (нет)
endif
|Конвейер B (Принимающий 1)|
:получил IData;

|Конвейер C (Принимающий 2)|
:ожидание;
|VirtualTransmitter|
:увеличение счётчика;
if (данные пришли?) then (да)
    :увеличение счётчика;
    if (получателей больше одного?) then (да)
        :отправить копию;
    else (нет — последний)
        :отпавить объект;
        :обнулить слот;
    endif
else (нет)
endif
|Конвейер C (Принимающий 2)|
:получил IData;

|VirtualTransmitter|
if (все получили?) then (да)
    :обновить счётчик;
else (нет)
endif

@enduml
